// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import DashCategoryPiechartController from "./dash_category_piechart_controller"
application.register("dash-category-piechart", DashCategoryPiechartController)

import DashExpenseChartController from "./dash_expense_chart_controller"
application.register("dash-expense-chart", DashExpenseChartController)

import DashIncomeChartController from "./dash_income_chart_controller"
application.register("dash-income-chart", DashIncomeChartController)

import DashSummaryChartController from "./dash_summary_chart_controller"
application.register("dash-summary-chart", DashSummaryChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
